USE [master]
GO

/****** Object:  Database [LevelUp]    Script Date: 13/10/2013 9:48:43 p.m. ******/
CREATE DATABASE [LevelUp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LevelUp] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LevelUp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LevelUp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LevelUp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LevelUp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LevelUp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LevelUp] SET ARITHABORT OFF 
GO

ALTER DATABASE [LevelUp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LevelUp] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LevelUp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LevelUp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LevelUp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LevelUp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LevelUp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LevelUp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LevelUp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LevelUp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LevelUp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LevelUp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LevelUp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LevelUp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LevelUp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LevelUp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LevelUp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LevelUp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LevelUp] SET RECOVERY FULL 
GO

ALTER DATABASE [LevelUp] SET  MULTI_USER 
GO

ALTER DATABASE [LevelUp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LevelUp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LevelUp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LevelUp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LevelUp] SET  READ_WRITE 
GO

