USE [master]
GO

CREATE LOGIN [LU_App] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[LevelUp], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [LU_Read] WITH PASSWORD=N'123', DEFAULT_DATABASE=[LevelUp], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [LU_SP] WITH PASSWORD=N'123', DEFAULT_DATABASE=[LevelUp], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [LU_No] WITH PASSWORD=N'123', DEFAULT_DATABASE=[LevelUp], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [LevelUp]
GO

CREATE USER [LU_App] FOR LOGIN [LU_App] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [LU_Read] FOR LOGIN [LU_Read] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [LU_SP] FOR LOGIN [LU_SP] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [LU_No] FOR LOGIN [LU_No] WITH DEFAULT_SCHEMA=[dbo]
GO

/****** Object:  User [db_execproc]    Script Date: 22/10/2013 4:58:57 p.m. ******/
CREATE ROLE [db_execproc] AUTHORIZATION [dbo]
GO
GRANT EXECUTE TO [db_execproc]
GO
EXEC sp_addrolemember N'db_execproc', N'LU_App'
GO
EXEC sp_addrolemember N'db_datareader', N'LU_Read'
GO
DENY CONNECT TO [LU_No]
GO
GRANT EXECUTE ON [dbo].[GetAllCurrency] TO [LU_SP]
GO