USE [master]
GO

CREATE LOGIN [LU_App] WITH PASSWORD=N'admin', SID = 0x40DCA2BC3F1F47458AA685D9F65F67FB, DEFAULT_DATABASE=[LevelUp], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [LU_Read] WITH PASSWORD=N'123', SID = 0x6D910DB3A3DBA140AC2A1260AAE4588E, DEFAULT_DATABASE=[LevelUp], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [LU_SP] WITH PASSWORD=N'123', SID = 0x86394255793AE54FB2E0F174E78E21C6, DEFAULT_DATABASE=[LevelUp], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [LU_No] WITH PASSWORD=N'123', SID = 0x3E1418A06BFE0F4498CAEBDEBEFEFED8, DEFAULT_DATABASE=[LevelUp], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [LevelUp]
GO

CREATE USER [LU_App] FOR LOGIN [LU_App] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [LU_Read] FOR LOGIN [LU_Read] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [LU_SP] FOR LOGIN [LU_SP] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [LU_No] FOR LOGIN [LU_No] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE ROLE [db_execproc] AUTHORIZATION [dbo]
GO

GRANT EXECUTE TO [db_execproc]
GO

EXEC sp_addrolemember N'db_execproc', N'LU_App'
GO

EXEC sp_addrolemember N'db_datareader', N'LU_Read'
GO

DENY CONNECT TO [LU_No]
GO

GRANT EXECUTE ON [dbo].[GetAllCurrency] TO [LU_SP]
GO